apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvapp
spec:
  selector:
    matchLabels:
      app: cvapp
  template:
    metadata:
      labels:
        app: cvapp
    spec:
      containers:
      - name: cvapp-cont
        image: corcoran909/cvapp
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000

