version: "3.8"
services:
  cvapp:
    image: corcoran909/cvapp
    ports:
    - target: 5000
      published: 5000
    deploy:
      replicas: 1
  db:
    image: corcoran909/mysql
    deploy:
      replicas: 1
    ports:
    - target: 3306
      published: 3306
  analytics:
    image: corcoran909/analytics
    ports:
    - target: 5000
      published: 8080
    deploy:
      replicas: 1
